<a href="https://colab.research.google.com/github/harshit-538/ML-DL/blob/main/3_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Gradient Descent**

- It is used mainly used to calculate weight&bias in logistic regression.
- calculates log loss/entropy and then update weights&bias in each epoch.(Back-propogate)
- Learning rate(generally 0.01) it helps to control change in log loss error.
- after each epoch, calculate derivative of log loss with respoct to all weights and bias and update it.

In [19]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import seaborn as sn
import pandas as pd

In [15]:
# Creating own Dataset

age = np.array([22,25,47,52,46,56,55,60,62,61,18,28,27,29,49,55,25,58,19,18,21,26,40,45,50,54,23,38])

affordibility = np.array([1,0,1,0,1,1,0,0,1,1,1,1,0,0,1,1,0,1,0,1,1,0,1,1,1,1,1,1])

bought_insurance = np.array([0,0,1,0,1,1,0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0])

In [16]:
df = np.column_stack((age,affordibility,bought_insurance))

In [20]:
df = pd.DataFrame(df,columns=['age','affordibility','bought_insurance'])

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [26]:
x_train_sclaed = X_train.copy()
x_train_sclaed['age'] = x_train_sclaed['age']/100

x_test_sclaed = X_test.copy()
x_test_sclaed['age'] = x_test_sclaed['age']/100

In [33]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(x_train_sclaed,y_train,epochs=5000)

Epoch 1/5000


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Streaming output truncated to the last 5000 lines.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.7727 - loss: 0.5226
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7727 - loss: 0.5226
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.7727 - loss: 0.5225
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7727 - loss: 0.5225
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.7727 - loss: 0.5225
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7727 - loss: 0.5224
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7727 - loss: 0.5224
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7727 - loss: 0.5223
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.7727 - loss: 0.5223
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.7727 - loss: 0.5223
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7727 - lo

In [34]:
model.evaluate(x_test_sclaed,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 1.0000 - loss: 0.3496


[0.3495520055294037, 1.0]

In [35]:
y_pred = model.predict(x_test_sclaed)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[0.71448576],
       [0.3552302 ],
       [0.16644086],
       [0.4814421 ],
       [0.7352926 ],
       [0.8386039 ]], dtype=float32)

In [36]:
coef,intercept = model.get_weights()
coef,intercept

(array([[5.2186155],
        [1.4324265]], dtype=float32),
 array([-2.9679046], dtype=float32))

use this coef and intercept from above


In [37]:
import math
def sigmoid(x):
  return 1/(1 + math.exp(-x));

In [39]:
def prediction_function(age,affordibility):
  weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
  return sigmoid(weighted_sum)

In [40]:
prediction_function(.47,1)

/tmp/ipython-input-3403181760.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1 + math.exp(-x));


0.7144857549709942

# **From Scratch**

In [41]:
def log_loss(y_true,y_pred):
  epsilon = 1e-15
  y_pred_new = [max(i,epsilon) for i in y_pred]
  y_pred_new = [min(i,i-epsilon) for i in y_pred_new]
  y_pred_new = np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [42]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

In [53]:
def gradient_descent(age,affordibility,y_true,epochs,threshold):
# it will return both coef and intercept
  w1 = w2 = 1
  bias = 0
  rate = 0.5
  n = len(age)

  for i in range(epochs):
    weighted_sum = w1*age + w2*affordibility + bias
    y_pred = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true,y_pred)

    w1d = (1/n)*np.dot(np.transpose(age),(y_pred-y_true))
    w2d = (1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))

    bias_d = np.mean(y_pred - y_true)

    w1 = w1 - rate * w1d
    w2 = w2 - rate * w2d
    bias = bias - rate * bias_d

    print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

    if loss <= threshold:
      break

  return w1,w2,bias

In [54]:
gradient_descent(x_train_sclaed['age'],x_train_sclaed['affordibility'],y_train,1000,0.4478)

Epoch:0, w1:0.9764914618862416, w2:0.9486331634521814, bias:-0.11313363930603333, loss:0.7084119128672071
Epoch:1, w1:0.9587026062366529, w2:0.9064130297174073, bias:-0.21174749413961003, loss:0.6786492072768174
Epoch:2, w1:0.946138713965328, w2:0.8726954052393727, bias:-0.2971520851994073, loss:0.6567392473954858
Epoch:3, w1:0.9382128977970783, w2:0.8466114305727271, bias:-0.3708639732681127, loss:0.6408666009607964
Epoch:4, w1:0.934309497124362, w2:0.8271890796951613, bias:-0.4344506647932769, loss:0.6294602516280402
Epoch:5, w1:0.9338314592222037, w2:0.8134495278910242, bias:-0.4894173390311499, loss:0.621258076714085
Epoch:6, w1:0.9362298786625239, w2:0.8044711793619568, bias:-0.5371381580451271, loss:0.6153012104735784
Epoch:7, w1:0.9410185713035398, w2:0.7994248197480652, bias:-0.5788240654287733, loss:0.6108908954225932
Epoch:8, w1:0.9477780991902104, w2:0.797587513217716, bias:-0.615515802880086, loss:0.6075333425347076
Epoch:9, w1:0.9561533285626389, w2:0.798342887708055, bias

(np.float64(5.205470296227018),
 np.float64(1.476759504742452),
 np.float64(-3.009889729264041))